const qwertyLayout = {
  ru: [
    [
      {
        key: 'ё',
        shiftKey: 'Ё',
        capsKey: 'Ё',
        code: 'Backquote',
      },
      {
        key: '1',
        shiftKey: '!',
        capsKey: '1',
        code: 'Digit1',
      },
      {
        key: '2',
        shiftKey: '"',
        capsKey: '2',
        code: 'Digit2',
      },
      {
        key: '3',
        shiftKey: '№',
        capsKey: '3',
        code: 'Digit3',
      },
      {
        key: '4',
        shiftKey: ';',
        capsKey: '4',
        code: 'Digit4',
      },
      {
        key: '5',
        shiftKey: '%',
        capsKey: '5',
        code: 'Digit5',
      },
      {
        key: '6',
        shiftKey: ':',
        capsKey: '6',
        code: 'Digit6',
      },
      {
        key: '7',
        shiftKey: '?',
        capsKey: '7',
        code: 'Digit7',
      },
      {
        key: '8',
        shiftKey: '*',
        capsKey: '8',
        code: 'Digit8',
      },
      {
        key: '9',
        shiftKey: '(',
        capsKey: '9',
        code: 'Digit9',
      },
      {
        key: '0',
        shiftKey: ')',
        capsKey: '0',
        code: 'Digit0',
      },
      {
        key: '-',
        shiftKey: '_',
        capsKey: '-',
        code: 'Minus',
      },
      {
        key: '=',
        shiftKey: '+',
        capsKey: '=',
        code: 'Equal',
      },
      { key: 'Backspace', code: 'Backspace', isModifier: true },
    ],
    [
      { key: 'Tab', code: 'Tab', isModifier: true },
      {
        key: 'й',
        shiftKey: 'Й',
        capsKey: 'Й',
        code: 'KeyQ',
      },
      {
        key: 'ц',
        shiftKey: 'Ц',
        capsKey: 'Ц',
        code: 'KeyW',
      },
      {
        key: 'у',
        shiftKey: 'У',
        capsKey: 'У',
        code: 'KeyE',
      },
      {
        key: 'к',
        shiftKey: 'К',
        capsKey: 'К',
        code: 'KeyR',
      },
      {
        key: 'е',
        shiftKey: 'Е',
        capsKey: 'Е',
        code: 'KeyT',
      },
      {
        key: 'н',
        shiftKey: 'Н',
        capsKey: 'Н',
        code: 'KeyY',
      },
      {
        key: 'г',
        shiftKey: 'Г',
        capsKey: 'Г',
        code: 'KeyU',
      },
      {
        key: 'ш',
        shiftKey: 'Ш',
        capsKey: 'Ш',
        code: 'KeyI',
      },
      {
        key: 'щ',
        shiftKey: 'Щ',
        capsKey: 'Щ',
        code: 'KeyO',
      },
      {
        key: 'з',
        shiftKey: 'З',
        capsKey: 'З',
        code: 'KeyP',
      },
      {
        key: 'х',
        shiftKey: 'Х',
        capsKey: 'Х',
        code: 'BracketLeft',
      },
      {
        key: 'ъ',
        shiftKey: 'Ъ',
        capsKey: 'Ъ',
        code: 'BracketRight',
      },
      {
        key: '\\',
        shiftKey: '/',
        capsKey: '\\',
        code: 'Backslash',
      },
      { key: 'Delete', code: 'Delete', isModifier: true },
    ],
    [
      { key: 'CapsLock', code: 'CapsLock', isModifier: true },
      {
        key: 'ф',
        shiftKey: 'Ф',
        capsKey: 'Ф',
        code: 'KeyA',
      },
      {
        key: 'ы',
        shiftKey: 'Ы',
        capsKey: 'Ы',
        code: 'KeyS',
      },
      {
        key: 'в',
        shiftKey: 'В',
        capsKey: 'В',
        code: 'KeyD',
      },
      {
        key: 'а',
        shiftKey: 'А',
        capsKey: 'А',
        code: 'KeyF',
      },
      {
        key: 'п',
        shiftKey: 'П',
        capsKey: 'П',
        code: 'KeyG',
      },
      {
        key: 'р',
        shiftKey: 'Р',
        capsKey: 'Р',
        code: 'KeyH',
      },
      {
        key: 'о',
        shiftKey: 'О',
        capsKey: 'О',
        code: 'KeyJ',
      },
      {
        key: 'л',
        shiftKey: 'Л',
        capsKey: 'Л',
        code: 'KeyK',
      },
      {
        key: 'д',
        shiftKey: 'Д',
        capsKey: 'Д',
        code: 'KeyL',
      },
      {
        key: 'ж',
        shiftKey: 'Ж',
        capsKey: 'Ж',
        code: 'Semicolon',
      },
      {
        key: 'э',
        shiftKey: 'Э',
        capsKey: 'Э',
        code: 'Quote',
      },
      { key: 'Enter', code: 'Enter', isModifier: true },
    ],
    [
      { key: 'Shift', code: 'ShiftLeft', isModifier: true },
      {
        key: 'я',
        shiftKey: 'Я',
        capsKey: 'Я',
        code: 'KeyZ',
      },
      {
        key: 'ч',
        shiftKey: 'Ч',
        capsKey: 'Ч',
        code: 'KeyX',
      },
      {
        key: 'с',
        shiftKey: 'С',
        capsKey: 'С',
        code: 'KeyC',
      },
      {
        key: 'м',
        shiftKey: 'М',
        capsKey: 'М',
        code: 'KeyV',
      },
      {
        key: 'и',
        shiftKey: 'И',
        capsKey: 'И',
        code: 'KeyB',
      },
      {
        key: 'т',
        shiftKey: 'Т',
        capsKey: 'Т',
        code: 'KeyN',
      },
      {
        key: 'ь',
        shiftKey: 'Ь',
        capsKey: 'Ь',
        code: 'KeyM',
      },
      {
        key: 'б',
        shiftKey: 'Б',
        capsKey: 'Б',
        code: 'Comma',
      },
      {
        key: 'ю',
        shiftKey: 'Ю',
        capsKey: 'Ю',
        code: 'Period',
      },
      {
        key: '.',
        shiftKey: ',',
        capsKey: '.',
        code: 'Slash',
      },
      { key: '▲', code: 'ArrowUp' },
      { key: 'Shift', code: 'ShiftRight', isModifier: true },
    ],
    [
      { key: 'Ctrl', code: 'ControlLeft', isModifier: true },
      { key: 'Win', code: 'MetaLeft', isModifier: true },
      { key: 'Alt', code: 'AltLeft', isModifier: true },
      { key: ' ', code: 'Space' },
      { key: 'Alt', code: 'AltRight', isModifier: true },
      { key: '◄', code: 'ArrowLeft' },
      { key: '▼', code: 'ArrowDown' },
      { key: '►', code: 'ArrowRight' },
      { key: 'Ctrl', code: 'ControlRight', isModifier: true },
    ],
  ],
  en: [
    // 1st row
    [
      {
        key: '`',
        shiftKey: '~',
        capsKey: '`',
        code: 'Backquote',
      },
      {
        key: '1',
        shiftKey: '!',
        capsKey: '1',
        code: 'Digit1',
      },
      {
        key: '2',
        shiftKey: '@',
        capsKey: '2',
        code: 'Digit2',
      },
      {
        key: '3',
        shiftKey: '#',
        capsKey: '3',
        code: 'Digit3',
      },
      {
        key: '4',
        shiftKey: '$',
        capsKey: '4',
        code: 'Digit4',
      },
      {
        key: '5',
        shiftKey: '%',
        capsKey: '5',
        code: 'Digit5',
      },
      {
        key: '6',
        shiftKey: '^',
        capsKey: '6',
        code: 'Digit6',
      },
      {
        key: '7',
        shiftKey: '&',
        capsKey: '7',
        code: 'Digit7',
      },
      {
        key: '8',
        shiftKey: '*',
        capsKey: '8',
        code: 'Digit8',
      },
      {
        key: '9',
        shiftKey: '(',
        capsKey: '9',
        code: 'Digit9',
      },
      {
        key: '0',
        shiftKey: ')',
        capsKey: '0',
        code: 'Digit0',
      },
      {
        key: '-',
        shiftKey: '_',
        capsKey: '-',
        code: 'Minus',
      },
      {
        key: '=',
        shiftKey: '+',
        capsKey: '=',
        code: 'Equal',
      },
      { key: 'Backspace', code: 'Backspace', isModifier: true },
    ],
    // 2nd row
    [
      { key: 'Tab', code: 'Tab', isModifier: true },
      {
        key: 'q',
        shiftKey: 'Q',
        capsKey: 'Q',
        code: 'KeyQ',
      },
      {
        key: 'w',
        shiftKey: 'W',
        capsKey: 'W',
        code: 'KeyW',
      },
      {
        key: 'e',
        shiftKey: 'E',
        capsKey: 'E',
        code: 'KeyE',
      },
      {
        key: 'r',
        shiftKey: 'R',
        capsKey: 'R',
        code: 'KeyR',
      },
      {
        key: 't',
        shiftKey: 'T',
        capsKey: 'T',
        code: 'KeyT',
      },
      {
        key: 'y',
        shiftKey: 'Y',
        capsKey: 'Y',
        code: 'KeyY',
      },
      {
        key: 'u',
        shiftKey: 'U',
        capsKey: 'U',
        code: 'KeyU',
      },
      {
        key: 'i',
        shiftKey: 'I',
        capsKey: 'I',
        code: 'KeyI',
      },
      {
        key: 'o',
        shiftKey: 'O',
        capsKey: 'O',
        code: 'KeyO',
      },
      {
        key: 'p',
        shiftKey: 'P',
        capsKey: 'P',
        code: 'KeyP',
      },
      {
        key: '[',
        shiftKey: '{',
        capsKey: '[',
        code: 'BracketLeft',
      },
      {
        key: ']',
        shiftKey: '}',
        capsKey: ']',
        code: 'BracketRight',
      },
      {
        key: '\\',
        shiftKey: '/',
        capsKey: '\\',
        code: 'Backslash',
      },
      { key: 'Delete', code: 'Delete', isModifier: true },
    ],
    // 3rd row
    [
      { key: 'CapsLock', code: 'CapsLock', isModifier: true },
      {
        key: 'a',
        shiftKey: 'A',
        capsKey: 'A',
        code: 'KeyA',
      },
      {
        key: 's',
        shiftKey: 'S',
        capsKey: 'S',
        code: 'KeyS',
      },
      {
        key: 'd',
        shiftKey: 'D',
        capsKey: 'D',
        code: 'KeyD',
      },
      {
        key: 'f',
        shiftKey: 'F',
        capsKey: 'F',
        code: 'KeyF',
      },
      {
        key: 'g',
        shiftKey: 'G',
        capsKey: 'G',
        code: 'KeyG',
      },
      {
        key: 'h',
        shiftKey: 'H',
        capsKey: 'H',
        code: 'KeyH',
      },
      {
        key: 'j',
        shiftKey: 'J',
        capsKey: 'J',
        code: 'KeyJ',
      },
      {
        key: 'k',
        shiftKey: 'K',
        capsKey: 'K',
        code: 'KeyK',
      },
      {
        key: 'l',
        shiftKey: 'L',
        capsKey: 'L',
        code: 'KeyL',
      },
      {
        key: ';',
        shiftKey: ':',
        capsKey: ';',
        code: 'Semicolon',
      },
      {
        key: "'",
        shiftKey: '"',
        capsKey: "'",
        code: 'Quote',
      },
      { key: 'Enter', code: 'Enter', isModifier: true },
    ],
    // 4th row
    [
      { key: 'Shift', code: 'ShiftLeft', isModifier: true },
      {
        key: 'z',
        shiftKey: 'Z',
        capsKey: 'Z',
        code: 'KeyZ',
      },
      {
        key: 'x',
        shiftKey: 'X',
        capsKey: 'X',
        code: 'KeyX',
      },
      {
        key: 'c',
        shiftKey: 'C',
        capsKey: 'C',
        code: 'KeyC',
      },
      {
        key: 'v',
        shiftKey: 'V',
        capsKey: 'V',
        code: 'KeyV',
      },
      {
        key: 'b',
        shiftKey: 'B',
        capsKey: 'B',
        code: 'KeyB',
      },
      {
        key: 'n',
        shiftKey: 'N',
        capsKey: 'N',
        code: 'KeyN',
      },
      {
        key: 'm',
        shiftKey: 'M',
        capsKey: 'M',
        code: 'KeyM',
      },
      {
        key: ',',
        shiftKey: '<',
        capsKey: ',',
        code: 'Comma',
      },
      {
        key: '.',
        shiftKey: '>',
        capsKey: '.',
        code: 'Period',
      },
      {
        key: '/',
        shiftKey: '?',
        capsKey: '/',
        code: 'Slash',
      },
      { key: '▲', code: 'ArrowUp' },
      { key: 'Shift', code: 'ShiftRight', isModifier: true },
    ],
    // the bottom row
    [
      { key: 'Ctrl', code: 'ControlLeft', isModifier: true },
      { key: 'Win', code: 'MetaLeft', isModifier: true },
      { key: 'Alt', code: 'AltLeft', isModifier: true },
      { key: ' ', code: 'Space' },
      { key: 'Alt', code: 'AltRight', isModifier: true },
      { key: '◄', code: 'ArrowLeft' },
      { key: '▼', code: 'ArrowDown' },
      { key: '►', code: 'ArrowRight' },
      { key: 'Ctrl', code: 'ControlRight', isModifier: true },
    ],
  ],
};

export default qwertyLayout;
